FROM --platform=linux/amd64 node:18-slim

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# Install app dependencies
RUN yarn install

RUN apt-get update && apt install -y openssl

# prisma global
RUN npm i -g prisma

RUN prisma generate

EXPOSE 3344

CMD [ "yarn", "dev" ]
